CREATE SCHEMA IF NOT EXISTS GUARDIAN_AI;

CREATE TABLE IF NOT EXISTS GUARDIAN_AI.DECISIONS (
    DECISION_ID VARCHAR(128) NOT NULL,
    OCCURRED_AT TIMESTAMP,
    SKU VARCHAR(128) NOT NULL,
    PRICE_INR DECIMAL(18, 2) NOT NULL,
    RISK_LEVEL VARCHAR(32) NOT NULL,
    REGRET_SCORE_INR DECIMAL(18, 2) NOT NULL,
    CONFIDENCE DECIMAL(8, 6) NOT NULL,
    INPUT_JSON VARCHAR(2000000) UTF8 NOT NULL,
    RECORD_JSON VARCHAR(2000000) UTF8 NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT DECISIONS_PK PRIMARY KEY (DECISION_ID)
);

CREATE TABLE IF NOT EXISTS GUARDIAN_AI.KNOWLEDGE_CHUNKS (
    CHUNK_ID VARCHAR(128) NOT NULL,
    SOURCE VARCHAR(512) UTF8 NOT NULL,
    TITLE VARCHAR(512) UTF8 NOT NULL,
    CONTENT VARCHAR(2000000) UTF8 NOT NULL,
    EMBEDDING_MODEL VARCHAR(128) UTF8 NOT NULL,
    EMBEDDING_JSON VARCHAR(2000000) UTF8 NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT KNOWLEDGE_CHUNKS_PK PRIMARY KEY (CHUNK_ID)
);
