import pandas as pd
import numpy as np
from pathlib import Path
# ============================================================
# Configuration
# ============================================================

RAW_FILE = Path(
    r"C:\Users\Riya\Downloads\online_retail\online_retail_II.xlsx"
)

OUTPUT_FILE = (
    Path(__file__).resolve().parent.parent
    / "data"
    / "training_data.csv"
)


# Minimum history required for a SKU to participate
MIN_OBSERVATIONS_PER_SKU = 30


# ============================================================
# Load data
# ============================================================

def load_data():
    print("Loading Year 2009-2010...")

    df_1 = pd.read_excel(
        RAW_FILE,
        sheet_name="Year 2009-2010",
        dtype={"StockCode": str},
    )

    print("Loading Year 2010-2011...")

    df_2 = pd.read_excel(
        RAW_FILE,
        sheet_name="Year 2010-2011",
        dtype={"StockCode": str},
    )

    df = pd.concat(
        [df_1, df_2],
        ignore_index=True,
    )

    print(f"Total raw transactions: {len(df):,}")

    return df


# ============================================================
# Basic cleaning
# ============================================================

def clean_data(df):
    print("\nCleaning data...")

    # Keep genuine sales only.
    # Negative quantities generally represent returns/cancellations.
    df = df[df["Quantity"] > 0].copy()

    # Prices must be positive.
    df = df[df["Price"] > 0].copy()

    # Product code must exist.
    df = df.dropna(subset=["StockCode"])

    # Explicit data types.
    df["StockCode"] = df["StockCode"].astype(str)
    df["InvoiceDate"] = pd.to_datetime(df["InvoiceDate"])

    print(f"Transactions after basic cleaning: {len(df):,}")

    return df


# ============================================================
# Remove non-product/service transactions
# ============================================================

def remove_non_products(df):
    print("\nRemoving known non-product records...")

    non_product_codes = {
        "POST",
        "DOT",
        "M",
        "ADJUST",
        "ADJUST2",
        "CRUK",
        "BANK CHARGES",
        "AMAZONFEE",
        "S",
        "PADS",
        "C2",
    }

    before = len(df)

    df = df[
        ~df["StockCode"]
        .str.upper()
        .isin(non_product_codes)
    ].copy()

    removed = before - len(df)

    print(f"Non-product rows removed: {removed:,}")

    return df


# ============================================================
# Aggregate by SKU + date + actual observed price
# ============================================================

def aggregate_observations(df):
    print("\nCreating SKU-day-price observations...")

    df["date"] = df["InvoiceDate"].dt.normalize()

    # Revenue generated by each transaction.
    df["revenue"] = df["Quantity"] * df["Price"]

    # Each row now represents:
    #
    #   SKU + date + actual observed price
    #
    # This avoids creating artificial average prices.
    daily = (
        df.groupby(
            [
                "date",
                "StockCode",
                "Price",
            ],
            as_index=False,
        )
        .agg(
            units_sold=("Quantity", "sum"),
            revenue=("revenue", "sum"),
            transaction_count=("Invoice", "nunique"),
        )
        .rename(
            columns={
                "Price": "price"
            }
        )
    )

    daily = daily.sort_values(
        ["StockCode", "date", "price"]
    ).reset_index(drop=True)

    print(
        f"SKU-day-price observations: {len(daily):,}"
    )

    return daily


# ============================================================
# Historical feature engineering
# ============================================================
def create_features(df):
    print("\nCreating historical features...")

    # --------------------------------------------------------
    # Current observations
    # --------------------------------------------------------

    df = df.sort_values(
        ["StockCode", "date", "price"]
    ).copy()

    # --------------------------------------------------------
    # Create SKU-day level history.
    #
    # This is separate from SKU-day-price observations.
    # It prevents one price observation on a day from
    # becoming the "previous observation" for another
    # price observation on the same day.
    # --------------------------------------------------------

    daily_history = (
        df.groupby(
            ["StockCode", "date"],
            as_index=False,
        )
        .agg(
            daily_units=("units_sold", "sum"),
            daily_revenue=("revenue", "sum"),
            daily_price=("price", "mean"),
        )
        .sort_values(
            ["StockCode", "date"]
        )
    )

    grouped = daily_history.groupby(
        "StockCode",
        group_keys=False,
    )

    # --------------------------------------------------------
    # Previous DAY features
    # --------------------------------------------------------

    daily_history["previous_units"] = (
        grouped["daily_units"]
        .shift(1)
    )

    daily_history["previous_price"] = (
        grouped["daily_price"]
        .shift(1)
    )

    # --------------------------------------------------------
    # Rolling demand
    #
    # IMPORTANT:
    # shift(1) prevents the current day's demand from
    # leaking into its own features.
    # --------------------------------------------------------

    daily_history["rolling_7d_units"] = (
        grouped["daily_units"]
        .transform(
            lambda x:
                x.shift(1)
                .rolling(
                    7,
                    min_periods=1,
                )
                .mean()
        )
    )

    daily_history["rolling_30d_units"] = (
        grouped["daily_units"]
        .transform(
            lambda x:
                x.shift(1)
                .rolling(
                    30,
                    min_periods=1,
                )
                .mean()
        )
    )

    # --------------------------------------------------------
    # Historical average price
    # --------------------------------------------------------

    daily_history["historical_avg_price"] = (
        grouped["daily_price"]
        .transform(
            lambda x:
                x.shift(1)
                .expanding()
                .mean()
        )
    )

    # --------------------------------------------------------
    # Keep only the historical features we need.
    # --------------------------------------------------------

    historical_features = daily_history[
        [
            "StockCode",
            "date",
            "previous_units",
            "previous_price",
            "rolling_7d_units",
            "rolling_30d_units",
            "historical_avg_price",
        ]
    ]

    # --------------------------------------------------------
    # Merge historical context into each actual
    # SKU-day-price observation.
    # --------------------------------------------------------

    df = df.merge(
        historical_features,
        on=["StockCode", "date"],
        how="left",
    )

    # --------------------------------------------------------
    # Price-relative features
    # --------------------------------------------------------

    # --------------------------------------------------------
    # Price relationship features
    # --------------------------------------------------------

    df["price_change"] = (
        df["price"]
        - df["previous_price"]
    )

    # Ratio is more useful than absolute price change
    # because a £1 change means very different things for
    # a £2 product versus a £100 product.
    df["price_ratio"] = (
        df["price"]
        / df["previous_price"].replace(0, np.nan)
    )

    # Current price relative to long-term SKU price
    df["price_vs_historical_avg"] = (
        df["price"]
        / df["historical_avg_price"].replace(0, np.nan)
    )

    # Log price helps the model capture multiplicative
    # pricing effects.
    df["log_price"] = np.log1p(
        df["price"]
    )

    # --------------------------------------------------------
    # Demand trend features
    # --------------------------------------------------------

    df["demand_trend"] = (
        df["rolling_7d_units"]
        / df["rolling_30d_units"].replace(0, np.nan)
    )

    # Absolute recent-vs-long-term demand difference
    df["demand_momentum"] = (
        df["rolling_7d_units"]
        - df["rolling_30d_units"]
    )

    # --------------------------------------------------------
    # Clean infinite values
    # --------------------------------------------------------

    df = df.replace(
        [np.inf, -np.inf],
        np.nan,
    )
    # --------------------------------------------------------
    # Calendar features
    # --------------------------------------------------------

    df["day_of_week"] = (
        df["date"].dt.dayofweek
    )

    df["month"] = (
        df["date"].dt.month
    )

    df["year"] = (
        df["date"].dt.year
    )

    df["is_weekend"] = (
        df["day_of_week"] >= 5
    ).astype(int)

    return df


# ============================================================
# Final filtering
# ============================================================

def final_filter(df):
    print("\nApplying final filters...")

    # --------------------------------------------------------
    # Remove rows without sufficient history.
    # --------------------------------------------------------

    history_columns = [
        "previous_units",
        "previous_price",
        "rolling_7d_units",
        "rolling_30d_units",
        "historical_avg_price",
    ]

    df = df.dropna(
        subset=history_columns
    ).copy()

    # --------------------------------------------------------
    # Keep SKUs with enough observations.
    # --------------------------------------------------------

    sku_counts = (
        df.groupby("StockCode")
        .size()
    )

    valid_skus = sku_counts[
        sku_counts >= MIN_OBSERVATIONS_PER_SKU
    ].index

    df = df[
        df["StockCode"].isin(valid_skus)
    ].copy()

    # --------------------------------------------------------
    # Keep SKUs with actual price variation.
    # --------------------------------------------------------

    price_counts = (
        df.groupby("StockCode")["price"]
        .nunique()
    )

    variable_price_skus = price_counts[
        price_counts >= 3
    ].index

    df = df[
        df["StockCode"].isin(variable_price_skus)
    ].copy()

    # --------------------------------------------------------
    # Sort final dataset.
    # --------------------------------------------------------

    df = df.sort_values(
        ["date", "StockCode", "price"]
    ).reset_index(drop=True)

    print(
        f"Final training observations: {len(df):,}"
    )

    print(
        f"Final SKUs: {df['StockCode'].nunique():,}"
    )

    return df


# ============================================================
# Save
# ============================================================

def save_data(df):
    OUTPUT_FILE.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    df.to_csv(
        OUTPUT_FILE,
        index=False,
    )

    print("\nSaved training data to:")
    print(OUTPUT_FILE)


# ============================================================
# Main
# ============================================================

def main():

    df = load_data()

    df = clean_data(df)

    df = remove_non_products(df)

    df = aggregate_observations(df)

    df = create_features(df)

    df = final_filter(df)

    save_data(df)

    print("\nData preparation complete!")


if __name__ == "__main__":
    main()